server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://innoforest.cktwvwfzgjx9.ap-northeast-2.rds.amazonaws.com/markOrder?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: innoforest
    password: yB90JSO4fiixlX6OQ4le
    driver-class-name: com.mysql.cj.jdbc.Driver