server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://markorder.c5y4salqda7s.ap-northeast-1.rds.amazonaws.com/markOrder?serverTimezone=Asia/Seoul
    username: markncompany
    password: markncompany!